const Message = {
  KAPIError: 'Something went wrong.',
  KRequiredFiledsEmpty: 'Please fill all the required details',
  KCredentialEmpty: 'Mobile number and password should not be empty',
  KMobileEmpty: 'Mobile number should not be empty',
  KMobileInvalid: 'Enter valid Mobile Number',
  KPasswordInvalid: 'Please Enter Password',
  KInvalidMobile: 'Invalid mobile number',
  KOTPEmpty: 'OTP should not be empty',
  KOTPInvalid: 'Invalid OTP',
  KAgreeTermsCondition: 'Please accept the terms & conditions',
  KNameEmpty: 'Name should not be empty',
  KImageSize: 'Select Maximum 3MB File size',
  KSpecialCharError: 'Special characters are not allow',
  KProfileEmpty: 'Profile should not be empty',
  KFirstNameEmpty: 'First name should not be empty',
  KLastNameEmpty: 'Last name should not be empty',
  KEmailEmpty: 'Email should not be empty',
  KEmailInvalid: 'Invalid email address',
  KDateOfBirthEmpty: 'Birth Date should not be empty',
  KVehicleMakeEmpty: 'Vehicle Make should not be empty',
  KModelEmpty: 'Model should not be empty',
  KVehicleNumberEmpty: 'Vehicle Number should not be empty',
  KDogCapacityEmpty: 'Dog Capacity should not be empty',
  KDrivingLicenseNoEmpty: 'Driving License Number should not be empty',
  KLicenseExpiryDateEmpty: 'License Expiry Date should not be empty',
  KLicensePlateEmpty: 'License Plate should not be empty',
  KInsuranceNumberEmpty: 'Insurance Number should not be empty',
  KVehicleRegistrationEmpty: 'Insurance Number should not be empty',
  KLicenseFrontImageEmpty: 'License Front Image should not be empty',
  KLicenseBackImageEmpty: 'License Back Image should not be empty',
  KLicenseAdsImageEmpty: 'License Ads Image should not be empty',
  KCheckInternetConnection: 'Please check internet connection.',
  KDogNameEmpty: 'Dog name should not be empty',
  KDogWeightEmpty: 'Dog weight should not be empty',
  KUploadImageEmpty: 'Please upload Image',
  KUploadDiscription: 'Please add Discription',
  KCheckbox: 'Please Agree Conditions',
  KDogBreedEmpty: 'Dog breed should not be empty',
  KDogCarrirEmpty: 'Dog carrir should not be empty',
  KHolderNameEmpty: 'Card Holder Name should not be empty',
  KCardNoEmpty: 'Card Number should not be empty',
  KEnterValidCardNo: 'Please Enter Valid Card Number',
  KExpDateEmpty: 'Card Expirey Date should not be empty',
  KCvvEmpty: 'Card CVV Number should not be empty',
  KEnterValidCvv: 'Please enter valid 3 digit cvv',
  KCardAndCvv: 'please check your card no. and cvv',
  KFeedback: 'please enter your feedback',
  KCancelTripReason: 'please enter your reason',
  KRating: 'please give rating '
};

export default Message;
